name: GBank
version: '${project.version}'
main: com.x32pc.github.GBank
api-version: '1.20'
commands:
  balance:
    description: Balance command
  bank:
    description: Bank command
  pay:
    description: Pay command
